version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recommend
      - POSTGRES_USER=aman
      - POSTGRES_PASSWORD=Ihatepasswords@1234
  recommender:
    build: .
    command: >
      bash -c
      "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
            - .:/recommender
    ports:
      - "8000:8000"
    depends_on:
      - db

