# Generated by Django 3.2.7 on 2021-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('autor_person_id', models.IntegerField()),
                ('author_country', models.CharField(blank=True, default='', max_length=60)),
                ('url', models.CharField(blank=True, default='', max_length=60)),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('event_strength', models.FloatField()),
            ],
        ),
    ]
