# Generated by Django 3.2.7 on 2021-10-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='person_id',
            field=models.CharField(blank=True, default='', max_length=90),
        ),
    ]
