# Generated by Django 3.2.7 on 2021-10-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('eventStrength', models.IntegerField()),
            ],
        ),
    ]
