# Generated by Django 3.2.7 on 2021-11-04 15:38

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_rename_content_id_popularity_contentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', jsonfield.fields.JSONField()),
            ],
        ),
    ]
